---
- name: Download Nerd Fonts
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item.filename }}"
    dest: "{{ download_dir }}/{{ item.filename }}"
    mode: "0644"
    timeout: 60
  loop: "{{ tool_sets.nerd_fonts }}"
  register: download_fonts_result
  until: download_fonts_result is success
  retries: 3
  delay: 2

- name: Extract Nerd Fonts
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/{{ item.filename }}"
    dest: "/usr/share/fonts/truetype"
    remote_src: true
  loop: "{{ tool_sets.nerd_fonts }}"
  become: true
  notify: Update font cache

- name: Install additional fonts via apt
  ansible.builtin.apt:
    name: "{{ tool_sets.additional_fonts.debian }}"
    state: present
  become: true
  notify: Update font cache
