---
- name: Download Nerd Fonts
  ansible.builtin.include_tasks: shared/utils/download_font.yaml
  loop: "{{ tool_sets.nerd_fonts }}"

- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ user_home }}/Library/Fonts"
    state: directory
    owner: "{{ username }}"
    mode: "0755"

- name: Extract Nerd Fonts
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/{{ item.filename }}"
    dest: "{{ user_home }}/Library/Fonts"
    remote_src: true
    owner: "{{ username }}"
  loop: "{{ tool_sets.nerd_fonts }}"

- name: Install additional fonts via Homebrew Cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ tool_sets.additional_fonts.macos }}"
  become_user: "{{ username }}"
  become: true
  register: fonts_cask_result
