---
# GUI applications for macOS
- name: Install GUI development tools
  ansible.builtin.include_tasks: darwin/dev_tools_gui.yaml
  when: (dev_tools_gui | bool) or (all | bool)

- name: Install general GUI software
  ansible.builtin.include_tasks: darwin/general_use_software_gui.yaml
  when: (gui | bool) or (all | bool)
