---
- name: Install Neovim via Homebrew
  community.general.homebrew:
    name: neovim
    state: present
    path: "{{ homebrew_path }}"
  register: brew_nvim_result
  until: brew_nvim_result is success
  retries: 3
  delay: 2
  become: false

- name: Create plugin manager directory
  ansible.builtin.file:
    path: "{{ nvim_plugin_manager_path }}"
    state: directory
    mode: "0775"
  become_user: "{{ username }}"
  become: true

- name: Install nvim plugin manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ nvim_plugin_manager_path }}/plug.vim"
    mode: "0644"
  register: download_plug_result
  until: download_plug_result is success
  retries: 3
  delay: 2
  become_user: "{{ username }}"
  become: true

- name: Create config directory
  ansible.builtin.file:
    path: "{{ nvim_config_path }}"
    state: directory
    mode: "0775"
  become_user: "{{ username }}"
  become: true

- name: Copy nvim config file
  ansible.builtin.copy:
    src: "{{ role_path }}/defaults/.config/nvim/init.vim"
    dest: "{{ nvim_config_path }}/init.vim"
    mode: "0644"
  become_user: "{{ username }}"
  become: true

- name: Delete Neovim plugin directory
  ansible.builtin.file:
    path: "{{ user_home }}/.vim/plugged"
    state: absent
  become_user: "{{ username }}"
  become: true

- name: Install/update Neovim plugins
  ansible.builtin.shell:
    cmd: |
      nvim +PlugInstall +qall
    executable: "{{ zsh_executable }}"
  become_user: "{{ username }}"
  become: true
  register: plug_install_result
  changed_when: "'Installing' in plug_install_result.stderr or 'Updating' in plug_install_result.stderr"
