---
# Development foundation: version control and editors
- name: Install and configure Git
  ansible.builtin.include_tasks:
    file: shared/git.yaml
    apply:
      tags: [git]

- name: Configure Neovim
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] | lower }}/nvim.yaml"
    apply:
      tags: [nvim, editors]
