---
# Cleanup and finalization
- name: Delete downloaded files
  ansible.builtin.include_tasks:
    file: shared/delete_downloaded_files.yaml
    apply:
      tags: [cleanup]

- name: Clean package cache (Debian only)
  ansible.builtin.include_tasks:
    file: debian/clean_apt.yaml
    apply:
      tags: [cleanup]
  when: ansible_facts['os_family'] == 'Debian'
