---
- name: Install SDKMan
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -s "https://get.sdkman.io" | bash
    executable: "{{ bash_executable }}"
  become_user: "{{ username }}"
  become: true
  register: sdkman_install
  changed_when: sdkman_install.rc == 0
