---
# Programming language environments
- name: Install Rust
  ansible.builtin.include_tasks:
    file: shared/rust.yaml
    apply:
      tags: [rust]
  when: (rust | bool) or (all | bool)
  tags: [always]

- name: Install Go
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] | lower }}/golang.yaml"
    apply:
      tags: [golang]
  when: (golang | bool) or (all | bool)
  tags: [always]

- name: Install Java
  ansible.builtin.include_tasks:
    file: shared/java.yaml
    apply:
      tags: [java]
  when: (java | bool) or (all | bool)
  tags: [always]
