---
# Programming language environments
- name: Install Rust
  ansible.builtin.include_tasks: shared/rust.yaml
  when: (rust | bool) or (all | bool)

- name: Install Go
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}/golang.yaml"
  when: (golang | bool) or (all | bool)

- name: Install Java
  ansible.builtin.include_tasks: shared/java.yaml
  when: (java | bool) or (all | bool)
