---
name: Ubuntu
on:
  push:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/ubuntu.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "post-installation/**/*"
      - ".github/workflows/ubuntu.yaml"
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ansible:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yaml

      - name: Run ansible playbook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd ${{ github.workspace }} && ansible-playbook ./playbook.yaml -e username=$(whoami) -e all=true -e github_token=$GITHUB_TOKEN
